### ISSUE TITLE
Error de login & Dotenv

### ISSUE THREAD

**Issue by rafamerino** [3clypse/milanuncios#10]
Gracias por tu trabajo. Al ejecutar el comando, me da error de login:
```
$ python renew.py
[10/09/2017 | 12:03:23] No se pudo iniciar sesión. Comprueba las credenciales.
```

He comprobado que en las variables de **renew.py**, como login se usa la url "https://www.milanuncios.com/cmd/", aunque al probar en la web, para hacer login me manda a "http://www.milanuncios.com/mis-anuncios/". 

Cambiar por esta url en el renew.py **no** soluciona el problema, y ya se me escapa qué más podría ser, mis conocimientos al respecto son muy limitados. Con el debug en True no encuentro mayor información que la que comento.

Las credenciales son correctas, accedo OK desde la web y las he puesto en **.env** haciendo copypaste.

=============================================

PS: Por cierto, en los requeriments se instala tanto "python_dotenv" como "dotenv", pero el sistema arroja error al tener ambos, creo que confunde librerías (no lo sé seguro, como comento, apenas tengo conocimientos de pyhton):
```
$  python renew.py
Traceback (most recent call last):
  File "renew.py", line 11, in <module>
    from dotenv import load_dotenv, find_dotenv
```

Tuve que hacer un: 
_pip uninstall dotenv_
_pip uninstall python-dotenv_
_pip install python-dotenv_

Para que funcionara OK.

**Comment by 3clypse** [comment]
Buenas, he corregido el problema con el dotenv, dejando la dependencia que no da fallos.

Sobre el problema del login no he podido reproducir tu error. Comprueba que no tenga caracteres extraños o prueba a ponerle comillas entre cada valor "email" y "contraseña"

**Comment by rafamerino** [comment]
Buenas,

He intentado de todas las maneras posibles y no logro hacer login. Pyhton, python2, pip, pip2, con la antigua versión de renew, con la nueva, con comillas, sin ellas...

Lo dejo por imposible. Gracias igualmente!
