### ISSUE TITLE
problem login

### ISSUE THREAD

**Issue by Arrheniu2** [3clypse/milanuncios#11]
tengo problemas en el login, creo que la pagina detecta algo raro con la conexion y te redirige a otra pagina

 <p>Please wait just a moment while we validate your browser.<br><br> This page will reload and show a pop-up asking you to confirm that you want to continue browsing.
        Confirming will allow you to proceed without further interruption.<br><br>If the page doesn't reload automatically, please
        <a href="javascript:window.location.reload();">click
        here</a>.</p>

y obtengo un error  No se pudo iniciar sesión. Comprueba las credenciales.

**Comment by 3clypse** [comment]
Intenta lo siguiente:
- Baja la nueva versión subida.
- Cambia la ip.
- Usa el script SÓLO 1 VEZ al día. (Esto es lo más importante)

**Comment by juanjetomas** [comment]
A mí me está dando el error "Error al acceder al índice. Cerrando el programa..." He intentado buscar la causa pero esa parte del código es la que menos entiendo. Gracias por todo, de antemano.

**Comment by Arrheniu2** [comment]
vale, parece que el login si funciona la primera vez, pero al intentar renovar los anuncios da un error de que requests.get esta recibiendo demasiados parametros, veo que en mi sistema (una raspbian ) tengo instalada la version 2.7 de requests, he instalado la 2.11 como se indica en los requerimientos del proeycto, pero desconozco que libreria se esta importando en tiempo de ejecucion. voy a ver si consigo encontrar el problema, lo malo que solo puedo provocar el fallo 1 vez al dia

**Comment by Arrheniu2** [comment]
lo he probado en otra maquina y funciona correctamente, cierro el issue, muchas gracias.
