### ISSUE TITLE
Error en el login

### ISSUE THREAD

**Issue by franmomentum** [3clypse/milanuncios#14]
Buenas al cargar el renew.py para renovar me da un error "No se puedo iniciar sesion. Comprueba las credenciales" las credenciales son correctas, tanto el correo como la contraseña, he probado con comillas dobles, comillas simples... pero nada sigue dando el error, si pudierais echarme una mano. Gracias

**Comment by franmomentum** [comment]
![image](https://user-images.githubusercontent.com/37030311/36940846-92298c98-1f4d-11e8-8da5-bb53dd8673e1.png)

**Comment by nadal28** [comment]
Tanto email como contraseña deberían ir sin comillas

**Comment by franmomentum** [comment]
ya me funcionó muchas gracias pero a la hora de renovar se renueva con éxito solo el primero y el resto dan errores debo modificar algo en el código?
Un saludo, gracias!
![sin titulo](https://user-images.githubusercontent.com/37030311/37146651-a91d4eec-22c4-11e8-915e-3f801a00eec1.jpg)

**Comment by nadal28** [comment]
El código no lo debes tocar, solo la parte de tu email y contraseña.

Prueba con otra cuenta que tengas de mil anuncios a ver si te pasa igual, de todas formas yo la ultima vez que lo he probado solo tengo un anuncio puesto

**Comment by programandoconro** [comment]
Hola, cuando le quito las comillas al email me da error por el arroba (@) ... 
'email': os.environ.get(email@gmail.com), invalid syntax

**Comment by programandoconro** [comment]
Ya resolví. Había que editar el archivo .env como bien dicen uds en las instrucciones que no leí. Allí se agregan las credenciales sin comillas ni dentro de <>, simplemente el texto del email y clave. Muchas gracias.
