### ISSUE TITLE
Error when renew ads

### ISSUE THREAD

**Issue by jopo79** [3clypse/milanuncios#2]
Hi:

I clone your project, It seems fantastic, but when I need renew and ads  I get this error:

2 anuncios obtenidos.
Renovando anuncio con referencia 202804653
Traceback (most recent call last):
  File "renew.py", line 89, in <module>
    main()
  File "renew.py", line 85, in main
    response = renew(cookie, values, id)
  File "renew.py", line 67, in renew
    response = requests.get(url['renew'], payload['renew'], cookies=cookie)
TypeError: get() takes exactly 1 argument (3 given)

I debug and check  this variables have  values url['renew'], payload['renew'], cookies=cookie.

I don't find the problem.

**Comment by 3clypse** [comment]
What version of python and requests are you using?

**Comment by jopo79** [comment]
Hi:
Python 2.7.6
Requests 2.2.1

Thanks in advance

**Comment by 3clypse** [comment]
You are using an old version of [requests](https://pypi.python.org/pypi/requests)

**Comment by jopo79** [comment]
what version should I use?

**Comment by jopo79** [comment]
Thanks, works peefect.

**Comment by 3clypse** [comment]
Fine. I will close the issue. 
Regards.
