### ISSUE TITLE
error -> Distil: Scrape Bot Protection

### ISSUE THREAD

**Issue by bravelord** [3clypse/milanuncios#9]
con las credenciales añadidas correctamente, no realiza la conexion

**Comment by 3clypse** [comment]
Hola, acabo de probarlo y están usando esto:
Distil: Scrape Bot Protection (https://www.distilnetworks.com/)
Ahora hay que ver si se puede saltar dicha protección o no...

**Comment by bravelord** [comment]
has comprobado si se puede? yo de momento no he podido unicamente a lo manual automatizado con bs y por coordenadas...

**Comment by 3clypse** [comment]
Hola, han quitado la protección (al menos de momento), por lo que funciona correctamente todo como debería.
Un saludo.

**Comment by bravelord** [comment]
buenas, tengo este problema ImportError: cannot import name load_dotenv
tengo el dotenv instalado y el virtualenv que puede faltar?

**Comment by 3clypse** [comment]
Acabo de reproducir la instalación y ejecución desde cero y no he obtenido fallo alguno.

En el README vienen explicados los pasos de instalación usando pip. 
Si tienes python3 instalado, tendrás que usar `pip2 install -r requirements.txt` para instalar las dependencias y luego `python2 renew.py` para ejecutarlo.
Asegurate también de que la variable de entorno .env esté creada y tenga las variables dentro.
